name: Second Workflow
 
on:
  repository_dispatch:
    types: [start-second-workflow]
  workflow_run:
    workflows: ["First Workflow"]
    types:
    -completed
    
 
jobs:
  run-second-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Run a second command
      run: echo "Running the second workflow"